# Generated by Django 5.1.3 on 2024-11-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_userbooks_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
