# Generated by Django 5.1.3 on 2024-11-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooks',
            name='returned_at',
        ),
    ]
